# Generated by Django 4.2.1 on 2023-06-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyTravel', '0002_remove_producto_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('fech_nac', models.DateField()),
                ('dni', models.IntegerField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Usuarios de EasyTravel',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
    ]
