# Generated by Django 4.2.1 on 2023-06-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyTravel', '0003_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='dni',
        ),
    ]
