# Generated by Django 4.2.1 on 2023-06-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyTravel', '0004_remove_usuario_dni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
